-- Copy and paste this into your SQL Editor in the Supabase Dashboard

-- 1. Create a table to store contact submissions
-- This stores the user's name, email, phone, message, etc.
create table public.submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  problem text,
  message text not null,
  status text default 'pending' -- default status is 'pending', can be 'resolved'
);

-- 2. Enable Row Level Security (RLS)
-- This is critical for security. It ensures your data is protected by policies.
alter table public.submissions enable row level security;

-- 3. Policy: Public Access
-- Allow anyone (even if not logged in) to INSERT a new submission.
-- "anon" is the role for unauthenticated users.
create policy "Allow public submissions" 
on public.submissions for insert 
to anon
with check (true);

-- 4. Policy: Admin View Access
-- Allow authenticated users (Admins) to VIEW all submissions.
-- "authenticated" is the role for logged-in users.
create policy "Allow admins to view submissions" 
on public.submissions for select 
to authenticated 
using (true);

-- 5. Policy: Admin Update Access
-- Allow authenticated users (Admins) to CHANGE status (e.g., mark as resolved).
create policy "Allow admins to update submissions" 
on public.submissions for update 
to authenticated 
using (true);

-- OPTIONAL: Create a 'profiles' table if you want to store admin details beyond auth.users
-- But for now, we'll just rely on creating a user in the Auth tab.
